# Generated by Django 3.0.6 on 2020-06-22 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=25, verbose_name='科目')),
                ('semes', models.TextField(choices=[('通年', '通年'), ('春夏', '春夏'), ('春クオーター', '春クオーター'), ('夏クォーター', '夏クォーター'), ('秋冬', '秋冬'), ('秋クォータ', '秋クォータ'), ('冬クォーター', '冬クォーター')], null=True, verbose_name='学期')),
                ('prof', models.CharField(default='', max_length=25, verbose_name='先生')),
                ('ease', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='楽単度')),
                ('aplus', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='評価A以上')),
                ('fulfil', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='内容')),
                ('test', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='小テスト')),
                ('exam', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='期末テスト')),
                ('cheat', models.TextField(choices=[('可', '可'), ('不', '不')], null=True, verbose_name='試験レジュメ持ち込み')),
                ('attend', models.TextField(choices=[('点呼', '点呼'), ('課題提出', '課題提出'), ('出席カード', '出席カード'), ('確認なし', '確認なし')], null=True, verbose_name='出席')),
                ('presen', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='プレゼン')),
                ('assig', models.TextField(choices=[('重', '重'), ('普', '普'), ('軽', '軽')], null=True, verbose_name='課題重さ')),
                ('comme', models.TextField(max_length=50, null=True, verbose_name='')),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 22, 8, 10, 12, 314455, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='SY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=25, verbose_name='科目')),
                ('semes', models.TextField(choices=[('通年', '通年'), ('春夏', '春夏'), ('春クオーター', '春クオーター'), ('夏クォーター', '夏クォーター'), ('秋冬', '秋冬'), ('秋クォータ', '秋クォータ'), ('冬クォーター', '冬クォーター')], null=True, verbose_name='学期')),
                ('prof', models.CharField(default='', max_length=25, verbose_name='先生')),
                ('ease', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='楽単度')),
                ('aplus', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='評価A以上')),
                ('fulfil', models.TextField(choices=[('★ 5', '★ 5'), ('★ 4', '★ 4'), ('★ 3', '★ 3'), ('★ 2', '★ 2'), ('★ 1', '★ 1')], null=True, verbose_name='内容')),
                ('test', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='小テスト')),
                ('exam', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='期末テスト')),
                ('cheat', models.TextField(choices=[('可', '可'), ('不', '不')], null=True, verbose_name='試験レジュメ持ち込み')),
                ('attend', models.TextField(choices=[('点呼', '点呼'), ('課題提出', '課題提出'), ('出席カード', '出席カード'), ('確認なし', '確認なし')], null=True, verbose_name='出席')),
                ('presen', models.TextField(choices=[('有', '有'), ('無', '無')], null=True, verbose_name='プレゼン')),
                ('assig', models.TextField(choices=[('重', '重'), ('普', '普'), ('軽', '軽')], null=True, verbose_name='課題重さ')),
                ('comme', models.TextField(max_length=50, null=True, verbose_name='')),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 22, 8, 10, 12, 376942, tzinfo=utc))),
            ],
        ),
    ]
