# Generated by Django 3.0.7 on 2020-06-22 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 22, 8, 31, 25, 863075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 22, 8, 31, 25, 925599, tzinfo=utc)),
        ),
    ]
