# Generated by Django 3.0.7 on 2020-07-01 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0002_auto_20200622_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='sy',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 8, 55, 30, 359759, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 8, 55, 30, 480997, tzinfo=utc)),
        ),
    ]
