# Generated by Django 3.0.7 on 2020-07-02 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0003_auto_20200701_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 8, 22, 41, 363622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 8, 22, 41, 498297, tzinfo=utc)),
        ),
    ]
