# Generated by Django 3.0.7 on 2020-07-03 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0004_auto_20200702_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 12, 10, 34, 395144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sy',
            name='contributor',
            field=models.TextField(max_length=50, null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 12, 10, 34, 494500, tzinfo=utc)),
        ),
    ]
