# Generated by Django 3.0.7 on 2020-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0006_auto_20200703_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.DateField(),
        ),
    ]
