# Generated by Django 3.0.7 on 2020-07-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0007_auto_20200704_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sy',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
