# Generated by Django 3.0.7 on 2020-07-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0008_auto_20200704_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sk',
            name='like',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sy',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
