# Generated by Django 3.0.7 on 2020-07-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0009_auto_20200705_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sy',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
