# Generated by Django 3.0.6 on 2020-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0013_auto_20200717_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bk',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bu',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ge',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ho',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jk',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ki',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ko',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ky',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='se',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sg',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sk',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='so',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sp',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sy',
            name='reply',
            field=models.TextField(default=0, null=True),
        ),
    ]
