# Generated by Django 3.0.6 on 2020-07-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0015_auto_20200717_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_comme', models.TextField(null=True, verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='bk',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='bu',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ge',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ho',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='jk',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ki',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ko',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='ky',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='se',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sg',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sk',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='so',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sp',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='sy',
            name='comme',
            field=models.TextField(null=True, verbose_name=''),
        ),
    ]
