# Generated by Django 3.0.6 on 2020-07-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_info', '0016_auto_20200718_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bk',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='bu',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='ge',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='ho',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='jk',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='ki',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='ko',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='ky',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='se',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sg',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sk',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='so',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='sy',
            name='contributor',
            field=models.TextField(null=True, verbose_name='投稿者'),
        ),
    ]
