# Generated by Django 3.0.7 on 2020-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200629_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
