# Generated by Django 3.0.7 on 2020-06-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mypage_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='user_id',
        ),
    ]
