# Generated by Django 3.0.7 on 2020-07-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_mypage_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='fav_prof',
        ),
    ]
