# Generated by Django 3.0.7 on 2020-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_mypage_fav_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypage',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
