# Generated by Django 3.0.6 on 2020-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mypage_re_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
